#List of flight and gate instances that the model can run.

#manually make a few flights and gates, for bug fixing
test_case = {"seed": 1,
    "flights": {"mode": "fixed",
        "list": [
            # flight_id, aircraft_size, entity, arr_time, arr_dest, dep_time, dep_dest, airline, arrival runway
            ("F1", "C", "passenger",  60, "domestic",      120, "domestic",      "A1", "01"),
            ("F2", "C", "passenger",  80, "international", 140, "international", "A1", "01"),
            ("F3", "B", "cargo",     100, "domestic",      160, "domestic",      "C1", "01"),
        ],
    },

    "gates": {"mode": "fixed",
        "list": [
            # gate_id, terminal_proximity, gate_size, entity, apron, corridor
            ("G1", "domestic",      "C", "passenger", "A", 1),
            ("G2", "international", "C", "passenger", "A", 1),
            ("G3", "convertible",   "F", "cargo",     "B", 1),
        ],
    },
}

#Reconstruct the case as in the paper
paper_case = {"seed": 42,
    "flights": {
        "mode": "generated",
        "horizon_start": 0,
        "horizon_end": 24 * 60,

        "n_flights": 1200,
        "sizes": {"B": 0.02, "C": 0.80, "D": 0.0, "E": 0.17, "F": 0.01},
        "entities": {"passenger": 0.90, "cargo": 0.10},
        "international_share": 0.20,
        "turnaround": {"B": 25, "C": 35, "D": 50, "E": 110, "F": 150,},
        "airlines": ["A1", "A2", "A3", "B1", "B2", "C1"],
        "Arrival_runways": ["01"]
    },

    "gates": {
        "mode": "apron_template",
        "apron_counts": {"A1": [8], 
                         "A2": [12], 
                         "A3": [11], 
                         "A4": [16],
                         "A5": [15],
                         "A6": [11],
                         "A7": [10],
                         "A8": [13],
                         "A9": [10],
                         "A10": [17],
                         "A11": [21],
                         "A12": [19],
                         "A13": [9],
                         "A14": [6],
                         "A15": [20],
                         "A16": [18],
                         "A17": [19],
                         "A18": [24],
                          }, 
        "terminal_proximity_share": {"domestic": 0.45, "international": 0.4, "convertible": 0.15,},
        "gate_sizes": {"B": 0.05, "C": 0.45, "D": 0.2, "E": 0.25, "F": 0.05}, #Dist of gate sizes
        "entities": {"passenger": 0.8, "cargo": 0.20},
    },

}

Paper_case_manuel = {"seed": 1,
    "flights": {"mode": "fixed",
        "list": [
            # flight_id, aircraft_size, entity, arr_time, arr_dest, dep_time, dep_dest, airline, arrival runway
            ("F1", "C", "passenger",  60, "domestic",      120, "domestic",      "A1", "01"),
            ("F2", "C", "passenger",  80, "international", 140, "international", "A1", "01"),
            ("F3", "B", "cargo",     100, "domestic",      160, "domestic",      "C1", "01"),
        ],
    },

    "gates": {"mode": "fixed",
              "gates_zggg": [
                #Cargo general
                ("Cargo 501", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 501L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 502", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 502L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 503", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 503L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 504", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 504L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 505", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 505L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 506", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 506L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 507", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 507L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 508", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 508L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 509", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 509L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 510", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 510L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 511", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 511L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 512", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 512L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 513", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 513L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 514", "convertible", "F", "cargo", "CARGO", 1),
                ("Cargo 514L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 515", "convertible", "D", "cargo", "CARGO", 1),
                ("Cargo 516", "convertible", "E", "cargo", "CARGO", 1),
                ("Cargo 517", "convertible", "E", "cargo", "CARGO", 1),
                ("Cargo 517L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 517R", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 518", "convertible", "E", "cargo", "CARGO", 1),
                ("Cargo 518L", "convertible", "C", "cargo", "CARGO", 1),
                ("Cargo 518R", "convertible", "C", "cargo", "CARGO", 1),

                #FBO Stands
                ("Fbo Stand Yl01", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yl02", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yl03", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yl04", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yl05", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yl06", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yl07", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yl08", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt01", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt02", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt03", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt04", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt05", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt06", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt07", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt08", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt09", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt10", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt11", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt12", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt13", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt14", "convertible", "B", "passenger", "FBO", 1),
                ("Fbo Stand Yt15", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt16", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt17", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt18", "convertible", "C", "passenger", "FBO", 1),
                ("Fbo Stand Yt19", "convertible", "B", "passenger", "FBO", 1),
                
                #Fedex stand
                ("Fedex 01", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 02", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 03", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 04", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 05", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 06", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 07", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 08", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 09", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 10", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 11", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 12", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 13", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 14", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 15", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 16", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 17", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 18", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 19", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 20", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 21", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 22", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 23", "convertible", "F", "cargo", "FEDEX", 1),
                ("Fedex 24", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 26", "convertible", "D", "cargo", "FEDEX", 1),
                ("Fedex 28", "convertible", "D", "cargo", "FEDEX", 1),
                
                #Remote stands
                #Remotes East-south
                ("Remote 301", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 302", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 303", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 304", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 305", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 306", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 307", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 308", "convertible", "E", "passenger", "REMOTE", 1),
                #Remote east-north
                ("Remote 309", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 310", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 311", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 312", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 313", "convertible", "C", "passenger", "REMOTE", 1),


                ("Remote 314", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 315", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 316", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 317", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 318", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 319", "convertible", "F", "passenger", "REMOTE", 1),
                ("Remote 319L", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 319R", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 320", "convertible", "F", "passenger", "REMOTE", 1),
                ("Remote 320L", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 320R", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 321", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 322", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 323", "convertible", "E", "passenger", "REMOTE", 1),

                #Remote West
                #Remote west-south
                ("Remote 401", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 402", "convertible", "E", "passenger", "REMOTE", 1),
                ("Remote 403", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 404", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 405", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 406", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 407", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 408", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 409", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 410", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 411", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 412", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 413", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 414", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 415", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 416", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 417", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 418", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 419", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 420", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 421", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 422", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 423", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 424", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 425", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 426", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 427", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 428", "convertible", "B", "passenger", "REMOTE", 1),
                ("Remote 429", "convertible", "B", "passenger", "REMOTE", 1),
                #Remote West-north
                ("Remote 432", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 433", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 434", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 435", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 436", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 437", "convertible", "C", "passenger", "REMOTE", 1),
                #Remote
                ("Remote 571", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 571L", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 571R", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 572", "convertible", "D", "passenger", "REMOTE", 1),
                ("Remote 572L", "convertible", "C", "passenger", "REMOTE", 1),
                ("Remote 572R", "convertible", "C", "passenger", "REMOTE", 1),
                
                #Terminal 1 South
                #Apron 
                ("Terminal 1, Gate 101", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 102", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 103", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 104", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 105", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 106", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 107", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 108", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 109", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 110", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 111", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 112", "domestic", "C", "passenger", "T1", 1),
                #Apron
                ("Terminal 1, Gate 113", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 114", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 115", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 116", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 117", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 118", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 119", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 120", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 121", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 122", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 123", "domestic", "C", "passenger", "T1", 1),
                #Apron
                ("Terminal 1, Gate 124", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 125", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 126", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 127", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 128", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 129", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 130", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 131", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 132", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 133", "domestic", "C", "passenger", "T1", 1),
                
                #Terminal 1 domestic gates - North
                #Apron
                ("Terminal 1, Gate 201", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 202", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 203", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 204", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 205", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 206", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 207", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 208", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 209", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 210", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 211", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 212", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 213", "domestic", "D", "passenger", "T1", 1),
                #Apron
                ("Terminal 1, Gate 214", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 215", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 216", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 217", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 218", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Gate 219", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 220", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 221", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 222", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 223", "domestic", "D", "passenger", "T1", 1),
                #Apron
                ("Terminal 1, Gate 224", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 225", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 226", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 227", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Gate 228", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 229", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 230", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 231", "domestic", "E", "passenger", "T1", 1),
                ("Terminal 1, Gate 232", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 233", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 234", "domestic", "D", "passenger", "T1", 1),
                ("Terminal 1, Gate 235", "domestic", "C", "passenger", "T1", 1),
                #Apron
                ("Terminal 1, Remote 135", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 136", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 137", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 138", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 139", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 140", "domestic", "F", "passenger", "T1", 1),
                ("Terminal 1, Remote 236", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 237", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 238", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 239", "domestic", "C", "passenger", "T1", 1),
                ("Terminal 1, Remote 240", "domestic", "E", "passenger", "T1", 1),

                ("Terminal 2, Gate 144", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 145", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 146", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 147", "international", "F", "passenger", "T2", 1),
                ("Terminal 2, Gate 147L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 147R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 148", "international", "D", "passenger", "T2", 1),
                ("Terminal 2, Gate 149", "international", "F", "passenger", "T2", 1),
                ("Terminal 2, Gate 149L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 149R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 150", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 151", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 152", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 153", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 154", "international", "F", "passenger", "T2", 1),
                ("Terminal 2, Gate 155", "international", "F", "passenger", "T2", 1),
                ("Terminal 2, Gate 156", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 157", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 158", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 159", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 160", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 160L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 160R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 161", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 162", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 163", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 164", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 165", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 166", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 167", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 168", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 169", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 170", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 171", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 172", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 173", "international", "E", "passenger", "T2", 1),

                ("Terminal 2, Gate 250", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 251", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 252", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 253", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 254", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 254L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 254R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 255", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 255L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 255R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 256", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 257", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 258", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 259", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 260", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 261", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 262", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 263", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 264", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 265", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 266", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 267", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 268", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 269", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 270", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 271", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 271L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 271R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 272", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 272L", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 272R", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 273", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 274", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 275", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 276", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Gate 277", "international", "F", "passenger", "T2", 1),
                ("Terminal 2, Gate 278", "international", "E", "passenger", "T2", 1),
                ("Terminal 2, Gate 279", "international", "E", "passenger", "T2", 1),

                ("Terminal 2, Remote 249", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Remote 430", "international", "C", "passenger", "T2", 1),
                ("Terminal 2, Remote 431", "international", "C", "passenger", "T2", 1),
            ]
        },
}
